import { theme as themeType, colorSwatch as colorSwatchType } from './types';
export declare const colors: {
    red: colorSwatchType;
    pink: colorSwatchType;
    purple: colorSwatchType;
    deepPurple: colorSwatchType;
    indigo: colorSwatchType;
    blue: colorSwatchType;
    lightBlue: colorSwatchType;
    cyan: colorSwatchType;
    teal: colorSwatchType;
    green: colorSwatchType;
    lightGreen: colorSwatchType;
    lime: colorSwatchType;
    yellow: colorSwatchType;
    amber: colorSwatchType;
    orange: colorSwatchType;
    deepOrange: colorSwatchType;
    brown: colorSwatchType;
    grey: colorSwatchType;
    blueGrey: colorSwatchType;
};
export declare const defaultTheme: themeType;
